### ISSUE TITLE
[Feature request] Apply sidebar zoom globally

### ISSUE THREAD

**Issue by BloodDragooner** [HooferDevelops/sidebar-zoom#1]
I see that the script works well, but it only applies to a single server and not each one, so perhaps it could be possible to set it on every server with a toggle? Thank you!

**Comment by HooferDevelops** [comment]
> I see that the script works well, but it only applies to a single server and not each one, so perhaps it could be possible to set it on every server with a toggle? Thank you!

It should be globally, however there may be an issue so I will have to check tomorrow and get back to you.

**Comment by HooferDevelops** [comment]
It seems as if I cannot reproduce this bug, if you could provide some more insight on how to do so, it would be much appreciated.

**Comment by BloodDragooner** [comment]
Sorry for the wait, but to me it looked as if it didn't change in servers with lots of channels, so it was my bad here. It's working well. Thank you for the help :)
